analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.378378
  lightness: 0.542792
  rhythmicContrast: 0.5
  saturation: 0.509009
cta: {}
layout_spectrum: 1
name: MostInspiringThing
opengraph: {}
purpose:
  - {}
typography_spectrum: 1
