analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.378378
  lightness: 0.576576
  rhythmicContrast: 0
  saturation: 0.626126
cta: {}
layout_spectrum: 0.439371
name: MostInspiringThing
opengraph: {}
purpose: {}
typography_spectrum: 1
