analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 1
  lightness: 0.074324
  rhythmicContrast: 0
  saturation: 1
cta: {}
layout_spectrum: 0
name: MostInspiringThing
opengraph: {}
purpose: {}
typography_spectrum: 1
