analytics: {}
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.378378
  lightness: 0.509009
  rhythmicContrast: 0.27027
  saturation: 1
cta: {}
layout_spectrum: 0.4393717030090599
name: MostInspiringThing
opengraph: {}
purpose: {}
typography_spectrum: 1
